import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import '../styles/global.scss'
import Header from '@/modules/header/Header'
import Footer from '@/modules/footer/Footer'
import ReactQueryProvider from '@/utils/Providers/ReactQueryProvider'
import ReduxProvider from './redux-provider'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ReactQueryProvider>
          <ReduxProvider>
            <Header />
            {children}
            <Footer />
          </ReduxProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
